[theme]
inherit = revealjs

[options]
clientcolor = rgb(72, 72, 94)
mainurl = /
logo = logo.png
backgroundcolor = rgb(239, 239, 246)
fonts = https://fonts.googleapis.com/css?family=Roboto
bodyfont = Roboto, sans-serif
headfont = Roboto, sans-serif
codefont = Roboto,"Andale Mono WT","Andale Mono","Lucida Console","Lucida Sans Typewriter","DejaVu Sans Mono","Bitstream Vera Sans Mono","Liberation Mono","Nimbus Mono L",Monaco,"Courier New",Courier,monospace